name: Profile summary cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/metrics.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          USERNAME: VPDPersonal
          BRANCH_NAME: main
          UTC_OFFSET: 3
          EXCLUDE: ""
          AUTO_PUSH: true
